language: csharp
node_js:
  - node
os: linux
mono: none
dist: trusty
sudo: required
dotnet: 1.0.1
install:
  - dotnet restore
  - cd ./src/Promact.TestCaseManagement && npm install
solution: "./Promact.TestCaseManagement.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - dotnet build --configuration Release
  - npm run tsc