language: csharp
dist: trusty
branches:
  only:
  - development
sudo: required
node_js:
  - node
os: linux
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - npm install
  - dotnet restore
solution: test.sln
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - dotnet build ./src/Promact.TestCaseManagement --configuration Release
  - cd ./src/Promact.TestCaseManagement && npm tsc