language: csharp
dist: trusty
branches:
  only:
  - development
sudo: required
node_js:
  - node
os: linux
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - npm install
  - dotnet restore
solution: test.sln
notifications:
  email: true
script:
  - dotnet build --configuration Release
  - cd src/Promact.TestCaseManagement && npm tsc