language: csharp
os: linux
mono: none
dist: trusty
sudo: required
dotnet: 1.0.3
before_install:
  - nvm install 7.9.0
  - nvm use 7.9.0
  - npm install -g npm
install:
  - dotnet restore
  - cd ./src/Promact.TestCaseManagement && npm install
solution: "./Promact.TestCaseManagement.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - dotnet build --configuration Release
  - cd ./wwwroot
  - npm run copy-compile