language: csharp
branches:
  only:
  - development
node_js:
  - node
os: linux
mono: none
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003131
install:
  - cd ./src/Promact.TestCaseManagement && npm install
  - dotnet restore
solution: "./test.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - dotnet build ./src/Promact.TestCaseManagement --configuration Release
  - cd ./src/Promact.TestCaseManagement && npm tsc